### ISSUE TITLE
Unable to protect existing folders with Private Bookmarks

### ISSUE THREAD

**Issue by Pfw51** [rharel/webext-private-bookmarks#106]
I just tried to use the Private Bookmarks add-on to protect some folders with links to my clients proprietary information.  The folders contain a significant number of links and it is implausible to start over.  In reading the overview of the add-on, I could not discern anything about folders that existed before downloading the add-on, and I could not find any instructions anywhere else.  So can you walk me through the basics?  Pretend I am not a techie and tell me step by step how to open the program and protect multiple folders.

I am using Firefox 66.0.3 64-bit on Windows 10-64.

**Comment by rharel** [comment]
1. Follow the initial instructions and choose a password 
2. Unlock using your chosen password; the Private Bookmarks folder appears.
3. Copy or cut existing bookmarks and paste into the Private Bookmarks folder.
4. Lock Private Bookmarks; the Private Bookmarks folder disappears.
5. Next time you unlock, the Private Bookmarks folder should contain the items you moved there in step (3).

DISCLAIMER: This software is something I maintain in my free time. It is not thoroughly tested, and is provided without guarantee of any kind. I emphasize this since it seems like you wish to use it for vital information. I encourage you to backup all important bookmarks before moving things to Private Bookmarks using Firefox' backup feature, accessible via:
1. Go to the Bookmarks menu (or Ctrl+Shift+B).
2. Select `Import and Backup` from the top (or Alt+I).
3. Select `Backup....` and save a backup of your bookmarks to a location on your PC.
4. If the backup contains sensitive info you wish to be encrypted, use other (tested) software to encrypt the backup file you saved in the previous step.
