### ISSUE TITLE
Bookmarks not available after restoration

### ISSUE THREAD

**Issue by amomanualidades** [rharel/webext-private-bookmarks#130]
The backup for my Firefox bookmarks lists the correct number of bookmarks including Private Bookmark folder, but after restoring it the files are no longer accessible.  On my Mac restoring bookmarks has successfully restored private bookmarks, though it has seemed gimmicky and I had to do it more than once for it to work.  Then I had to reinstall the add-on, restore the bookmarks, and move the old private bookmarks folder into the new private bookmarks folder as a sub folder.  On my PC they won't restore at all.  I've removed the add-on and reinstalled, and I've tried to restore more than once.

I do want the auto backup to back these bookmarks up, but it does seem like they should need the add-on activated with a matching previous password for them to be visible again.  I don't know if that is possible.  I think on the Mac it just made them visible after restore, but I was able to add them to the hidden folder.  Of course that creates a security issue as an easy work around to view the bookmarks.

Problem: Backup did not restore bookmarks, though the number of bookmarks restored includes the invisible bookmarks.
Suggestion: Auto-backup, restore, but require add-on to have a matching password to the time of the backup.  

Everything is up to date on my computer.  I'm running Windows 10, and the most recent Firefox.  I'm not a Mac person...I know I don't have the most recent OS, but the previous one.  Firefox is up to date on the Mac too.

**Comment by rharel** [comment]
If I understand you correctly, your issue is with Firefox' auto backup mechanism not restoring Private Bookmarks. I am not in control over how that feature of Firefox behaves and therefore cannot make any promises with regards to what or when things work there. 

What I recommend is to backup Private Bookmarks separately through the export feature on PB's options page. And also restore these exported files when needed using the import feature on PB's options page.

**Comment by amomanualidades** [comment]
Thank you for the explanation.

 
 

Sent: Tuesday, February 04, 2020 at 1:12 PM
