### ISSUE TITLE
A Couple of Suggestions

### ISSUE THREAD

**Issue by StormFX** [rharel/webext-private-bookmarks#29]
I love the add-on. I'm glad someone finally got it right. I would like to offer a few suggestions, though:

- Multiple encrypted "folders", distinguished by the assigned password (and perhaps a name, only shown after unlocking, of course). Basically, you click "Unlock", enter the password for "Folder One", which only unlocks that folder. To open additional folders, you have to enter the password for each, separately. This would add a layer of security such that if you were coerced into supplying a password, you could provide one with less sensitive data and no one would be the wiser.

- Allow other characters in the password. Limiting to alpha-numeric characters limits the security. At least allow non-whitespace characters like the dash and underscore.

- Allow the addition of a button separate from the Bookmarks Menu button that lists exclusively the currently unlocked private bookmarks in a menu like the Bookmarks menu. Obviously, the button would be invisible until it was unlocked.

Not sure if any of these are feasible, but I figured it couldn't hurt to ask. :)

**Comment by rharel** [comment]
Great feedback, my response one item at a time:

1. The problem with multiple folders is that I'm afraid of the cases where users share a FF profile (I know you're not supposed to, but I've seen that happen a lot). What happens then if they decide to name two folders the same, unaware another user already chose that name? Of course we cannot let the user know the name had already been chosen. There are ways to work around this, like requiring a username in addition to folder + password, or having the extension assign random names to the folder and have the user be given the responsibility to remember them. But these workarounds compromise usability quite a bit. If I could be sure that the above case (where users share a FF profile) is an extremely small minority, I would reconsider. But that requires some survey, so perhaps in the next release we could prompt with a link to one. I've opened #30 to remind me of this.

2. That is fair. I've opened #31 for this.

3. A separate button is not possible due to technical limitations of extensions. The closest we can do is a sidebar, but then you lose favicons. Another option is to add the unlocked folder to the bookmarks toolbar for easy access - but problem is not all users have that toolbar enabled. Is opening the bookmarks menu and viewing the Private Bookmarks from the folder as it is now a major inconvenience to you or is it minor?

**Comment by rharel** [comment]
Also just to let you know: Even if we do eventually decide to allow for multiple folders, that is a change that requires a HUGE amount of work and time to happen. So it won't be anytime soon I'm afraid :(

**Comment by StormFX** [comment]
Thanks for the response!

1. The unique ID for separate folders could be the password (or a hash thereof), not the folder name itself. This would prevents overrides unless they're using the same password which would be bad anyhow. As far as displaying the name, I'm not sure that would really be a problem as Firefox allows the same folder names to appear (I believe it uses its ID field), with the name being a non-unique field.

2. Admittedly, I'm not fully aware of the limitations of add-ons in regards to the recent UI changes. If it's just that you're limited to a single toolbar button with a menu, you could simply have an option to show the private bookmarks in the default menu (make the buttons smaller and put them on the right side of the header section with the menus in the area where they are now. Eg:

`Private Bookmarks          [U][R][C]
-----------------------------------
Folder 1 > Folder One Menu
Folder 2 > Folder Two Menu
-----------------------------------
Version, etc                               [S]`

Where U = Unlock, R = Reset Password  and C = Clear Data (but icons obviously) and then folder 1, 2, etc, are the separately unlocked folders, if that makes sense. That said, it's a minor thing. It makes sense to utilize the Bookmarks toolbar (I know use it).

I realize that multiple folders would take a lot of work. Obviously, the best add-ons are those that keep things simple. So it you want to scrap that idea, feel free. I just figured it would add some additional options and security.

Speaking of security, it's probably a bad idea to have the "Clear Data" button in the drop-down. Someone could easily walk by and wipe everything while you're in the john, etc. I realize it's necessary to have it available in the case of lost passwords, etc, but it would probably be better on the settings page. :)

**Comment by rharel** [comment]
This gives me a lot to think about, thanks! To address your points:

### Multiple folders
Yes, using the same passwords is bad, but I guarantee we will have instances of that happening, and people will come here with pitchforks when that happens. I put the multiple folders idea on hold, until I can come up with a design that is both usable and safe against all crazy edge-cases.

Another option is to forget about it altogether and tackle your motivation for this request: you wanted to be able to supply a mock password to some decoy data. For this to be addressed we need just one additional password and some user-supplied file with decoy bookmarks.

### Listing bookmarks outside of bookmarks menu
What you suggest seems to me like duplicating a lot of functionality that the browser already does for us, and the amount of bloat and effort this will add is in my opinion not in proportion to the potential benefits. What you are really asking for here is for the search bar in the bookmarks menu to be able to search on "folders" or something similar.

However, I do like having a checkbox at the options page that when active causes the folder to appear in the toolbar rather than under "Other Bookmarks", I'm not sure yet if it is technically feasible (whether the tools available to extensions allow it), but I've opened #32 to track this.

### The location of the "Clear Data" button
My rebuttal to this is:
 -  If you leave your device open when there are malicious people around then the blame here for the loss of data is at least 50/50 :)
 - If someone is malicious enough to snoop around they will find the button on the options page as well.
 - Data loss can be prevented using the data-export function on the options page.

Also, if you find yourself needing to clear data in a hurry then the extra 5 seconds it takes getting over to the options page might be too long.

**Comment by StormFX** [comment]
**Multiple folders:

I'll leave you to figure that out. You clearly know what you're doing. :)

**Bookmarks outside of menu:

Not sure where you got the searching part, but that's not what I meant at all. I was simply suggesting a toolbar button that lists, exclusively, the private bookmarks. If that so happens to be accessible via the Bookmarks Toolbar, that works for me. Though after testing it out, if you unlock it, move it to the toolbar and then lock it again, the next unlock moves it back to the menu. The option to choose where it appears would be great, as long as it retains the proper order (IE, if I have it at position one, it should be at position one each time I unlock it).

**Clear Data button:

I'll use your profile sharing argument here. If you and your significant other share the same profile and they see you have "private" bookmarks, they could easily delete them. While admittedly, they could do so from the options menu, it would take more work to do so. I suppose my issue with it is that in order to unlock the folder, you have to have the button on the toolbar, which also also makes the Clear Data button easily accessible.

In any regard, these are merely suggestions on my part. Whether or not you implement them is up to you. I'm simply throwing out ideas. ;)

**Comment by rharel** [comment]
### Bookmarks outside of menu
Yes I understood what you wanted, all I'm saying is that if you could search by folder, then the listing of *just* private bookmarks would be really easy to get. You bring up an excellent point about maintaining order within the parent folder though - I will take this into account.

### Clear data button
Ah I now better understand what you are saying. There are two solutions to this: 
1. Make the Private Bookmarks panel accessible through a keyboard shortcut (opens in a tab instead of a popup), so that you can remove the Private Bookmarks button from the toolbar (it will still be visible in the `Customize...` view so I'm not sure how good of a solution this is).
2.  Add another instance of the "clear data" button to the options page, but retain the option to either show/hide a second instance where it is now (to avoid making users who like the present configuration angry). 

I'll think about it!

Your feedback was very productive, thanks again. I'm marking this discussion closed since I think we've addressed everything, but if you have anything else to contribute you can of course still comment and I will see it.

**Comment by StormFX** [comment]
A hotkey to unlock it would be logical (CTRL+Shift+U). Whether it opens a tab or pop-up doesn't really matter, though a dialog would make more sense. Not sure if that's possible with the UI restrictions, though.

As far as the other, you could simply have the options available in the popup also on the Options page and then add an option to toggle (show/hide) the button itself (Perhaps via CSS ID). I suppose if it comes down to it, the user could implement a UserChrome (CSS) hack to hide it.

Anyhow, thank you for time and considering my suggestions. I appreciate the effort you've put into this. :)

**Comment by rharel** [comment]
Unfortunately I think neither a dialog nor the ability to completely show/hide the button itself is available. Dem extension restrictions are cramping my style...

You're welcome! Most of your suggestions will be in the next release, I just need to find the time to work on them. Have a good one.
