### ISSUE TITLE
Extension default folder location

### ISSUE THREAD

**Issue by jacobmartin03** [rharel/webext-private-bookmarks#47]
Hello, first of all, thank you for this useful extension.
Recently, I reset my Windows, but I forgot to save my private bookmarks.
There's still my windows.old folder, obviously, and I would like to not modify/replace my new profile to the ancient one and stuff.
So, here's my question : How can I transfer your extension's data to my new Firefox profile? Where's the location of all of this?

Thanks in advance,
Martin.

**Comment by rharel** [comment]
Private Bookmarks stores your data in your profile, so as far as I know on Windows 10 that would be at `C:\Users\<your username>\AppData\Roaming\Mozilla\Firefox\Profiles\<your profile>\browser-extension-data\private-bookmarks@rharel` - I suppose it was moved to be under `Windows.Old` somewhere (I have never reset Windows, so am not sure).

So provided you get hold of your old `private-bookmarks@rharel` folder here is what you can do:
1. Install Private Bookmarks in Firefox.
2. Close Firefox.
3. Copy the old `private-bookmarks@rharel` to under the `browser-extension-data\` in the new profile (choose to overwrite when asked).
4. The next time you open Firefox, it should load all your old settings and bookmarks and let you unlock as usual.

Let me know if that worked for you! Otherwise provided you have your old `private-bookmarks@rharel` folder and the `storage.js` file within, we can try another way to import your bookmarks.

**Comment by jacobmartin03** [comment]
I think Firefox actually just reseted my storage.js file, so I've lost my bookmarks 😭 
My bad anyway, I should have not cut it, should have copied it before.
Thanks a lot for your quick reply btw !

**Comment by rharel** [comment]
Oh no I'm sorry to hear that :( When I tried these steps on a brand new profile it worked for me (order is very important though, the storage resets when the extension installed). Either way, happy new year!
