### ISSUE TITLE
Password no longer working

### ISSUE THREAD

**Issue by wuwu4u** [rharel/webext-private-bookmarks#58]
For bug reports, please fill in:
 - Firefox version: ? 58.0 (64-Bit)
 - Operating system: ? Win 10 prof 64
 - Steps to reproduce: ?

the password is not longer working.
It works for appr. 3 weeks.

 - What was the expected behavior: ?

 - What was the actual behavior: ?

It is assumed that you are using the latest version of Private Bookmarks.

**Comment by rharel** [comment]
I'm sorry to hear that, that is the first time a problem like that is reported. It is also very surprising to me, since the last time I changed anything that has to do with (un)locking was months ago.

So, assuming that you made sure no CAPS-lock was on, and that you were using the right keyboard language, it is very hard for me to understand what the problem might be (especially since it is the first time I hear of this).

When was the last time you unlocked and it did work?
Does your password have any unusual characters (like letters with accents etc.)?
If you export your data and try to import it again, does the password also not work?

**Comment by rharel** [comment]
Also, do you get an error message or does the password field just flash red?

**Comment by sclark89** [comment]
I have encountered this problem as of this morning, too. I know that I am entering the password correctly, but the password field flashes red when I try to authenticate. I'm using Firefox 58.0.2, Windows 7 64-bit, and the program has been working flawlessly for months now.
