### ISSUE TITLE
Password Suddenly Not Working

### ISSUE THREAD

**Issue by sclark89** [rharel/webext-private-bookmarks#59]
- Firefox version: 58.0.2 64-bit
 - Operating system: Windows 7 64-bit
 - Steps to reproduce: Tried logging in to unlock my bookmarks
 - What was the expected behavior: Opening my private bookmarks menu
 - What was the actual behavior: Despite entering password correctly, the password field flashes red and does not unlock my bookmarks. It has been working correctly for months and I was able to use it as recently as yesterday.

**Comment by rharel** [comment]
Thanks for the report. It seems you hit some sort of fringe edge-case where the conditions and timing need to be just right to expose some bug. If you could help me find out what it is I'd be grateful. 

First of all, export your data into a backup file from the options page (don't overwrite any previous backups you've made - in case your data in its current state got corrupted, any backup you make now will be useless, so keep the old backups). 

Some questions that might give me a clue:
1. If you reinstall the extension, setup a new password (same as the old one) and import the exported backup file, does the password not work as well?
2. If you do the same but with an older backup file, does it work then?
3. If you can remember yesterday (the last time it worked), did you add/remove/move some content in the folder and immediately close the browser?  
4. Do you make use of the syncing feature?
5. Your data is stored in your Firefox profile folder, that is: `C:\Users\{Your Username}\AppData\Roaming\Mozilla\Firefox\Profiles\{Your Profile}\browser-extension-data\private-bookmarks@rharel` in a file `storage.js`, ideally I would love to have it and your password so I could inspect (`admin<at>rharel<dot>com`), but of course since it contains sensitive information I understand you may not want to trust a stranger with it. But if you could tell me how big of a file it is (how many KB)?

In any case, just knowing that this bug exists is a big help. But without a clear way to reproduce it is very difficult for me to get an idea of what it might be, though I will keep looking. Sorry for the inconvenience.

**Comment by rharel** [comment]
For (1) and (2): Sorry my bad, it might be that if you reinstall without restarting the browser after uninstall your data won't be truly reset. If you could try this instead:
a. Use the clear data function in the options page.
b. Then setup a new password and unlock the bookmarks with the password you have just set up.
c. Now try to import the backups, both the (presumably) corrupted one and older ones. 

Regarding:
3. That seems to me to be the most promising lead we have so far. My initial suspicion is that if the browser is closed while your bookmarks are in the process of being encrypted/saved (which takes only a very short while indeed, confirming the role of [un]luck in this) then perhaps Firefox does not guard against corruption.
4. I see, then that's not it.
5. Alright, no problem.

Thank you for sticking around.

**Comment by sclark89** [comment]
So after trying the clear data function, I was able to set up a new password and import a backup. Unfortunately it was not the backup I made this morning (that didn't seem to work), but rather an older one. It looks like we're working perfectly now, and closing after altering the bookmarks does sound very promising.

**Comment by rharel** [comment]
That's good to hear. If our suspicion is correct, a workaround would be to make sure there are a few seconds between a change to the contents of the folder and closing the browser (right now whenever a change occurs, a second or so later an hourglass overlay appears over the extension's icon, and it disappears in theory when encryption/saving is complete, so try not to close the browser while that hourglass is shown).

I don't think there's anything more you can do for me here, so thanks again for your help :) I will try to find some spare time to investigate this more thoroughly in the coming weekend.

**Comment by sclark89** [comment]
Thanks!

**Comment by dksakkos** [comment]
Any suggestions when there are no backups? I successfully reset my password but import doesn't work - says incorrect password.

**Comment by rharel** [comment]
Unfortunately I don't have any. The latest version (released just now) has the option for periodic reminders to make a backup though, maybe that'll prevent loss of bookmarks in the future.
