### ISSUE TITLE
Syncing bookmarks using 3rd parties?

### ISSUE THREAD

**Issue by kapekod** [rharel/webext-private-bookmarks#60]
Love love love the app. –How to sync the Private-Bookmarks, using a third party bookmark manager, I use XMarks. Does each browser need to be unlocked? If so, is there an easier way to do it without unlocking each one?

**Comment by kapekod** [comment]
Did my question disappear?

**Comment by rharel** [comment]
No, it was in the title, but I edited your post now to make things more clear. 

The problem with using a third-party bookmark syncing service is that while the folder is locked, the bookmarks are literally removed from the browser's collection and instead are stored as an encrypted blob in your Firefox profile folder. There is no way for other extensions to access Private Bookmark's storage space so XMarks won't find them, and even if it could access it they are still encrypted and XMarks won't be able to read that format.

When you unlock the folder, I assume XMarks will sync it across your devices, but then again the moment you lock it the bookmarks are deleted from the browser and XMarks will sync that deletion across your devices as well...

I assume you are using XMarks because you are syncing across different browsers, but Private Bookmarks exists only for Firefox, and by design is not an online service so all your data remains on your machine for you to have maximum privacy and control over it.

If you are only concerned with syncing across Firefox, I recommend trying the experimental syncing feature in Private Bookmark's options page.

Sorry I couldn't be of more help. Does the above answer your question?
