### ISSUE TITLE
Error during browser action initialization

### ISSUE THREAD

**Issue by teh64190** [rharel/webext-private-bookmarks#63]
Debug info: `Could not establish connection. Receiving end does not exist.`

Running Mac OS X v. 10.12.6 and Firefox 59.0.2

**Comment by teh64190** [comment]
Debug info: Could not establish connection. Receiving end does not exist.
Running Mac OS X Sierra v.10.12.6 and Firefox 59.0.2

**Comment by teh64190** [comment]
Tried the extension again today, 12 hours later. Private Bookmarks folder not appearing in Library. When PB is activated I get the attached 2 windows in sequence. No unlock window appears. PB folder still missing.

![pb_screenshot_1-window_when_activated](https://user-images.githubusercontent.com/38677352/39198375-c491f140-479b-11e8-8eb9-b46ac67103f9.jpg)

![pb_screenshot_2-bookmarks_locked_confirm](https://user-images.githubusercontent.com/38677352/39198382-c99f0394-479b-11e8-8b22-89e1818c485e.jpg)

**Comment by teh64190** [comment]
Hi Raoul,

It was working like a charm after installation. This is a recent issue. I don’t think I changed anything in my Browser setup. I will see if I have a Backup I can restore from and will let you know if I need any help with that. Thank you!

T O M
—
Tom Holownia

**Comment by teh64190** [comment]
Hi. So, I was able to export the encrypted file: encrypted_private_bookmarks.json
When I attempt to Import it with it’s password, the Import button does not change to a dark blue clickable button (see attached screen shot).
I am certain of the password.
Next steps? Thanks for the help.

T O M
—

**Comment by rharel** [comment]
Here is what I would recommend:

1. Firstly, if you have backup files from when the extension was still working, hang on to those since if somehow the extension's data got corrupted any backup you make now will probably not have much use.

2. Next, make a backup copy of the extension's data file (though I suspect it is corrupted anyway, still to be safe we should do it). On Mac you can find it in either:
* `~/Library/Application Support/Firefox/Profiles/<your profile>/browser-extension-data/private-bookmarks@rharel` or
* `~/Library/Mozilla/Firefox/Profiles/<your profile>/browser-extension-data/private-bookmarks@rharel`
The file is called `storage.json`.

3. Now, as for the `encrypted_private_bookmarks.json` file you mentioned, you can't import it because importing requires unlocked bookmarks (but you can't unlock, that's the problem!). So first use the `Clear data` option from PB's options page to reset the extension.

4. Now open the main panel and choose a password.
5. Unlock using the password you have just chosen.
6. Now try to import the backup file.
7. If that doesn't work, I guess the file is corrupted, so try to import one of the older ones (if you have any) from when the extension still worked, hopefully that'll work.

It's quite late where I live and I'm off to bed, let me know how it goes and I'll read it tomorrow. Fingers crossed!

**Comment by teh64190** [comment]
Raoul,

Thank you for the step-by-step, which I will review and retain.

When I restored a previous backup of my bookmarks the Private Folder appeared and I was able to access it without the use of the add-on.

I’m now re-installing the add-on to see if the problem persists.

T O M
—
Tom Holownia

**Comment by teh64190** [comment]
Hi Raoul,

Just wanted to close the loop with you on this.
All is well. 
I was able to recover the bookmarks from a backup and when I reinstalled the add-on it seems to be running fine.
I’ll let you you know if I run into any other hiccups.
Thanks again for the help.
And thank you for the add-on! :-)

T O M
—

**Comment by rharel** [comment]
Thanks for the update. Glad you managed to restore your bookmarks. One last thing: another issue that a different person had comes to mind: the symptoms were not quite the same, but the result was (corrupted data, resort to reset + backup). The best clue I've gotten about what might be causing this corruption is if you change something in the folder (add/remove/move/edit an item) and then close the browser right after, possibly interrupting PB while it saves the changes to disk. Perhaps something similar happened in your case. Anyway a workaround is to give it two-three seconds after a change before closing the browser (there should be no hourglass hovering over the main extension button). Maybe that'll help prevent a recurrence of the problem in the future. Cheers!

**Comment by teh64190** [comment]
Got it. Thanks for the heads-up.

T O M
—
